-- ============================================================
-- PASO 13 · Lista de invitados de cumpleaños (imán de contactos)
-- ------------------------------------------------------------
-- El organizador del cumple carga a cada invitado desde la web.
-- Por cada niño invitado guardamos SIEMPRE un adulto responsable
-- con su teléfono → el local se queda esa base de contactos
-- (posibles clientes futuros). Con esos datos se generan las
-- tarjetitas de invitación (mismo diseño, solo cambia el nombre).
-- ============================================================

create table if not exists birthday_guests (
  id               bigint generated by default as identity primary key,
  created_at       timestamptz not null default now(),
  -- datos del cumple (se repiten en cada invitado para agrupar)
  cumple_nombre    text,             -- festejado/a
  cumple_telefono  text,             -- WhatsApp del organizador
  cumple_fecha     date,
  -- invitado
  nino_nombre      text not null,    -- nombre del niño invitado
  nino_detalle     text,             -- detalle extra para la tarjeta
  -- adulto responsable (OBLIGATORIO) = el contacto que se queda el local
  adulto_nombre    text not null,
  adulto_telefono  text not null,
  confirmado       boolean not null default false
);

create index if not exists idx_birthday_guests_cumple on birthday_guests (cumple_telefono, cumple_nombre);

-- Seguridad: la web (rol anónimo) sólo puede INSERTAR; leer sólo el staff.
alter table birthday_guests enable row level security;

drop policy if exists "invitados_insert_publico" on birthday_guests;
create policy "invitados_insert_publico" on birthday_guests
  for insert to anon with check (true);

drop policy if exists "invitados_select_staff" on birthday_guests;
create policy "invitados_select_staff" on birthday_guests
  for select to authenticated using (public.mi_rol() in ('dueno', 'gerente', 'contador'));

drop policy if exists "invitados_update_staff" on birthday_guests;
create policy "invitados_update_staff" on birthday_guests
  for update to authenticated using (public.mi_rol() in ('dueno', 'gerente')) with check (public.mi_rol() in ('dueno', 'gerente'));

grant insert on birthday_guests to anon;
grant select, update on birthday_guests to authenticated;
